name: 'CI'
on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    if: github.event_name  == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM
        run: |
          npm install
      - name: Run NPM
        run: |
          npm run all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          XRAY_USERNAME: ${{ secrets.XRAY_USERNAME }}
          XRAY_PASSWORD: ${{ secrets.XRAY_PASSWORD }}
          
  test:
    if: github.event_name  == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Run imports"
        uses: ./
        with:
          username: ${{ secrets.XRAY_USERNAME }}
          password: ${{ secrets.XRAY_PASSWORD }}
          xrayCloud: "false"
          xrayBaseUrl: "https://xray-demo3.xpand-it.com"
          testFormat: "junit"
          testPaths: "marathon_tests/*.xml"
          testExecKey: "GHXA-9"
          projectKey: "GHXA"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: "configs/configuration_repo.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

